sudo: false

language: c

os:
    - osx
    - linux

compiler:
    # we don't require a C compiler! if we don't specify one here, we get extra builds,
    # for both gcc and clang
    - gcc

env:
    # Test with our internal pypi mirror
    - PIP_FIND_LINKS=http://pypi.pub.build.mozilla.org/pub
      PIP_NO_INDEX=1
      DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)
      PIP_STRICT_VERSIONS=--strict
    # ... and with the official pypi website
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)
      PIP_STRICT_VERSIONS=

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /sbin/start-stop-daemon --start --quiet --make-pidfile --pidfile /tmp/custom_xvfb_99.pid --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x768x24 ; fi

install:
    - python .travis/create_venv.py ~/.venv
    - source ~/.venv/bin/activate

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --config ./.pep8.rc --exclude=client .

    # Prepare the build and everything else
    - ./.travis/before_script.sh

script:
    # Run in non-e10s mode
    - firefox-ui-tests --installer *firefox-* --gecko-log -

    # Run in e10s mode
    - firefox-ui-tests --installer *firefox-* --gecko-log - --e10s

notifications:
    irc:
        - "irc.mozilla.org#automation"
