language: python

python:
    - 2.7

env: DISPLAY=:99

before_install:
    - sudo apt-get update
    - "/sbin/start-stop-daemon --start --quiet --make-pidfile --pidfile /tmp/custom_xvfb_99.pid --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24"

install:
    - sudo apt-get install flashplugin-nonfree
    - python setup.py develop
    - pip install mozdownload pep8

before_script:
    - pep8 greenlight

    # Download Firefox Nightly which is compatible with the used version of
    # marionette client
    - mozdownload -t daily --date 2014-12-18
    - tar -xvf *firefox*.tar.bz2

script:
    - run-greenlight-tests --binary firefox/firefox

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"